---
author: pvwebmonk
comments: true
date: 2013-08-04 17:37:01+00:00
layout: post
slug: mara-and-the-buddha-embracing-our-suffering
title: Mara and the Buddha – Embracing our Suffering
wordpress_id: 2616
categories:
- Transcriptions
tags:
- ananda
- buddha
- buddhata
- embracing
- enemies
- flowerness
- friends
- garbage
- mara
- suffering
---

Thich Nhat Hanh

Dear friends, today is the 6th of August, 1996 and we are in the Upper Hamlet. We are going to speak English today.

I would like to tell you a story that took place a number of years ago. One day I saw the Venerable Ananda—you know who he is? Ananda is a cousin of the Buddha, a very handsome man with a very good memory. He memorized everything the Buddha said, and after the Buddha passed away, he repeated exactly what the Buddha said during his life. Then other monks tried to learn and memorize also. Later on, all this was put down into writing and that is why we have the Sutras today. “Sutras” means the teaching of the Buddha in written form. They exist in Pali, Sanskrit, Chinese, Tibetan, and in Vietnamese, but originally it was in a kind of Bengali, very close to Pali and Sanskrit.

One day I saw the Venerable Ananda practicing walking meditation in front of the hut of the Buddha. You know, Ananda became a monk, a student of the Buddha. He was the attendant of the Buddha during many years. He took very good care of the Buddha. Of course, the Buddha loved him and there were people who were jealous of him. Sometimes Ananda was so concerned about the happiness of the Buddha that he forgot about himself. Sometimes he did not enjoy what was there in the present moment, being much younger than the Buddha.

One day standing on the hill looking down, the Buddha saw beautiful rice fields. The rice was ripe, about to be harvested. But because Ananda was only thinking of how to make the Buddha comfortable, he didn't see it. So the Buddha pointed to the rice fields below and said, “Ananda can you see it's beautiful?” It was like a bell of mindfulness—suddenly Ananda saw that the rice fields down there were so beautiful. The Buddha smiled and said, “Ananda, I want the robes of the monks and the nuns to be designed in the form of rice fields—golden colors like the rice that is already ripe, small portions of the rice fields like that.” Ananda said, “Yes, that is possible, I will go tell my brothers and from now on we will make the sanghati, the robes of the monks and nuns, in the form of rice fields.”

Another time when Ananda was with the Buddha, north of the Gangha River in the city of Vaisali, the Buddha pointed to the city, the trees, and the hills, and said to Ananda “Don't you see Vaisali is beautiful?” Then Ananda took the time to look at the beauty of the city.

The day I saw Ananda practicing walking meditation around the hut of the Buddha, he was trying to protect the Buddha from guests. Many guests came, and they always wanted to have a cup of tea with the Buddha, and the Buddha could not just receive guests all day. So Ananda was trying to help. That day Ananda was practicing walking around the hut of the Buddha. It's not exactly a hut, but a cave—the Buddha was staying in a cave, very cold. And Ananda saw someone coming, coming, coming in his direction.

He had the impression that he knew this person, but just forgot his name. When that person had come very close, he recognized him as Mara. You know Mara? Mara is the one who had caused the Buddha a lot of difficulties. The night before the Buddha attained final enlightenment, Mara was there to tempt him. Buddha was tempted by Mara. Mara is the tempter. He always wanted the Buddha to be a politician, to be a king, or a president, or a foreign minister, or running a business, having a lot of money, a lot of beautiful women; and he was always trying to tempt the Buddha so that Buddha would go into these directions. That is Mara.

Ananda saw Mara approaching. He felt uncomfortable. Why should Mara come at this time? But Mara saw him already—Ananda could not hide himself—so he had to stand there and wait for Mara and they had to say things like, “Hello, how do you do?” People say that even if they don't like each other. They say, “Hello, good morning, how are you,” and so on. They don't mean it. Then they come to the real thing: “What are you here for Mara?" “I want to visit the Buddha,” Mara said, “I want to see him.” Ananda said, “Why should you want to see the Buddha? I don't think the Buddha has time for you.”

You know when the head of a corporation or a director of an office doesn’t want to see you she says, “Go and tell him I am in conference.” And Ananda was about to say something like that, but he remembered that he had to practice the Five Precepts and could not tell a lie. So he refrained from saying that the Buddha is in conference. He was frank. He said, “Mara, why should the Buddha see you? What is the purpose and are you not ashamed of yourself? Don't you remember that in the old days, under the Bodhi tree, you were defeated by the Lord? How could you bear seeing him again? I don't think that he will see you. You are the enemy of the Buddha,” and Ananda continued to say what was really in his heart.

You know Mara was very aware, a very experienced person. He just stood there and looked at the young Venerable Ananda and smiled. After Ananda finished, he said, “What did you say Ananda, you said the Buddha has an enemy?” Then Ananda felt very uncomfortable to say that the Buddha had an enemy. That did not seem to be the right thing to say, but he just said it. He said, “I don't think that the Buddha will see you, you are his enemy,” So if you are not very concentrated, very deep, very mindful, you may say things like that against yourself, against what you know and what you practice. When Mara heard Ananda say that he is the enemy of the Buddha, he burst out laughing and laughing and laughing, and that made Ananda very uncomfortable. “What, you’re telling me that the Buddha also has enemies?"

So finally Ananda was defeated, completely defeated. He had to go in and announce the visit of Mara, hoping that the Lord would say, “I have no time for him, I need to continue sitting.” But to his surprise, the Buddha smiled beautifully and said, “Mara, wonderful! Ask him to come in.” That surprised Ananda. Remember Ananda was young with not a lot of experience. All of us are Ananda, you know. So Ananda had to go out again and bow to Mara and ask him to come in because the Lord wanted Mara to be his guest.

The Buddha stood up, and guess what? The Buddha did hugging meditation with Mara. Ananda did not understand. The Buddha invited Mara to sit on the best place in the cave—a stone bench. And he turned to his beloved disciple and said, “Ananda, please make tea for us.” You might guess that Ananda was not entirely happy. Making tea for the Buddha—yes. He could do that 1,000 times a day. But making tea for Mara was not a very pleasant idea. But since the Lord had asked, Ananda went into a corner and began to make tea for them and tried to look deeply, why things were like that.

When the tea was offered to the Buddha and the guest, Ananda stood behind the Buddha and tried to be mindful of what the Buddha would need. You see, if you become a novice, you have to practice being an attendant to your teacher. You stand behind him or her and you try to know what your teacher needs each moment. But it did not seem that the Buddha needed anything. He just looked at Mara in a very loving way and he said, “Dear friend, how have you been? Is everything okay?" Mara said “No, not okay at all. Things go very badly with me. You know something Buddha, I'm very tired of being Mara. Now I want to be someone else, like you. You are kind, wherever you go you are welcome. You are bowed to with lotus flowers, and you have many monks and nuns with very lovely faces following you. You are offered bananas and oranges and kiwis and all kinds of fruits.

“As a Mara I have to wear the appearance of a Mara. Everywhere I go I have to speak in a very tricky language. I have to show that I am really Mara. I have to use many tricks, I have to use the language of Mara, I have to have an army of wicked little Maras and if I breathe in and breathe out, every time I breathe out I have to show that smoke is coming from my nose. But I don't mind very much all these things. What I mind most is that my disciples, the little Maras, are beginning to talk about transformation and healing. They’re beginning to talk about liberation, Buddhahood. That's one thing I cannot bear. So I have come to propose to you that we exchange roles. You be a Mara and I'll be a Buddha.”

When the Venerable Ananda heard that, he was very scared. Oh, his heart was about to stop! What if his teacher accepted the exchange of roles? He would be the attendant of a Mara. So he was hoping that the Buddha would refuse the proposal. Then the Buddha looked at Mara very calmly, smiling to him, and asked this question: “Mara, do you think it's a lot of fun being a Buddha? People don't understand me—they misunderstand me and put a lot into my mouth that I have never said. They have built temples where they put statues of me in copper, in plaster, sometimes in emerald, in gold. And they attract a lot of people who offer them bananas, oranges, citrus, and a lot of things.

“Sometimes they carried me on the street in a procession and I was sitting on a cart decorated with flowers, doing like this—like a drunk person. I don't like being a Buddha like that. So you know, in the name of the Buddha—in my name—they have done a lot of things that are very harmful to the Dharma. You should know that being a Buddha is also very difficult. If you want to be a teacher and if you want people to practice the Dharma correctly, that is not an easy job. I don't think that you would enjoy being the Buddha. The best thing is for each of us to stay in his or her own position and try to improve the situation and enjoy what we are doing.”Then the Buddha, in order to summarize all that he just said, read to Mara a verse, a gatha. But the gatha is a little bit too long, I don't remember. The essence of the gatha is just what I have said in the former part of the story.

If you were there with Ananda and if you were very mindful, you would have had the feeling that Buddha and Mara were a couple of friends who need each other—like day and night, like flowers and garbage. This is a very deep teaching of Buddhism, and I trust that the children will understand—very deep. You may compare Buddha with the flowers, very fresh, very beautiful. And you may compare Mara with the garbage. It doesn't smell good. There are a lot of flies who like to come to the garbage. It's not pleasant to touch, to hold in your hand, to smell the garbage.

Yet all flowers become garbage. That is the meaning of impermanence: all flowers have to become garbage. If you practice Buddhist meditation, you find out about very interesting things—like about the garbage. Although garbage stinks, although garbage is not pleasant to hold in your hand, if you know how to take care of the garbage, you will transform it back into flowers. You know gardeners don't throw away garbage. They preserve the garbage and take care of the garbage, and in just a few months the garbage becomes compost. They can use that compost to grow lettuce, tomatoes, and flowers. We have to say that organic gardeners are capable of seeing flowers in garbage, seeing cucumbers in garbage. That is what the Buddha described as the non-dualistic way of looking at things.

If you see things like that, you will understand that the garbage is capable of becoming a flower, and the flower can become garbage. Thanks to the flowers there is garbage, because if you keep flowers for three weeks they become garbage, and thanks to the garbage there will be flowers. You now have an idea of the relationship between Buddha and Mara. Mara is not very pleasant, but if you know how to help Mara, to transform Mara, Mara will become Buddha. If you don't know how to take care of the Buddha, Buddha will become Mara.

You see there are people who, in the beginning, love each other very much. They believe that without each other they cannot survive. Their love is so important. They cling to each other because they think that love between them is the only element that can help them survive. But because they don't know how to preserve the love and take care of their love, they get angry at each other, they misunderstand each other, and later on love is transformed slowly into hate. There are those who say, “I hate you, I don't want to see you anymore, I wish you would die.” Those people in the past had proclaimed that they needed each other, they could not survive without each other, they loved each other, so love transforms into hatred. It's like a kind of flower transformed into garbage.

So what you learn today is very deep. Flowers and garbage are of an organic nature because both flowers and garbage are living realities. Buddha and Mara are also organic, and they need each other. It is thanks to the difficulties, thanks to the temptations, that the Buddha has overcome his suffering and his ignorance and become a fully enlightened being. The day before yesterday, I gave a Dharma talk on suffering, and I said that if you look deeply into the nature of your suffering, you will find a way out of it. So if you want a flower, you have to use the garbage. That is why the people who suffer a lot now should not be discouraged. Suffering is their garbage. If they know how to take good care of their garbage they will be able to make the flower come back to them, the flower of peace, of joy. The Buddha shows us the way to do so.

When I was in Moscow several years ago, we offered a retreat to Muscovites, and a few Christians from Korea held a kind of a retreat very close to ours. Some of them came to our friends and asked why they should follow the Buddha. The reason we should not follow the Buddha, according to them, is that Buddha is a mortal. “Mortal” means someone who has to die. In their mind what we need is someone who will not die. Since the Buddha is someone who has to be born and who has to die, he cannot help us—that is the meaning of the declaration made by those friends.

I think it's a wonderful thing to die, because if you are born and you die, it means you are a living reality, like the flower and the garbage: they are living things. We are for life. Anything that is not born, not dying, not growing, is not alive. To be alive means to be born, to grow, to get old, to die, to be born again, to grow, to get old, to die and to continue like that. How do you expect life to be possible without change? But there is one thing that the children may like to know. There is a difference between “flower” and “flowerness.”

The flower may die, but not the flowerness. Even if a flower has become garbage, you know you can bring the flower back. If you are a good gardener, if you know how to use compost, seeds, water, you will be able to bring the flower back. This means a flower may die, but flowerness is something that is there all the time: because flowerness is not a thing, flowerness is the nature of a thing. So it is with Buddha and Buddha nature. Buddha nature is called in Sanskrit buddhata. We all have buddhata inside of us, this Buddha nature. If we want, we can make the Buddha be born every moment in our hearts. That is a very wonderful thing. You can make the Buddha be born in your heart every moment, because you have Buddhahood in you, you have the nature of the Buddha in you. Buddha is a living thing: Buddha is born, Buddha grows up, Buddha hides himself away, Buddha dies. But Buddhahood is there in us.

We might think that terms like “Buddha nature” are difficult because we don’t know that this is something very simple, very simple. Children can understand very well. We have flowerness in us; we have “garbageness” in us also. Don’t think that they are two enemies—no. They look like enemies—Ananda was not very skillful in seeing that—but they can support each other. In Buddhism, there is no fight between good and evil—that is the most wonderful thing in the Buddhist practice! There is no fight between good and evil. Good and evil are both organic matters. If you have understanding and wisdom, you will know how to handle both the flower and the garbage in you, you can make the Buddha be born every moment of your life, and peace and happiness will be possible. This is a very deep Dharma talk for young people. I hope that you will be able to deepen your understanding of this Dharma talk. Your big brothers and sisters and the Dharma teachers will help you. This may be a very important lesson that you will learn in your life.

[To the children:] When you hear the bell, please stand up and bow to the Sangha before you go out.

[Bell. Children leave]

In the beginning of this year’s summer opening, we reflected on the fact that, for healing to take place in our body and in our soul, we have to learn how to allow our body and our consciousness to rest. That is the practice of stopping, of calming in order for healing to start. We talked about the animals in the jungle. When they are wounded or get sick, they always look for a quiet and safe place to lie down. They just lie down for many, many days. The animals do not think of hunting or eating or doing anything, because they feel they need to rest and they know that only resting can bring healing. They don’t think of eating at all.

We humans we might think that if we don’t eat anything, we grow weak and we cannot heal. We are not as wise as these animals, because fasting is a very wonderful way to help the body and also the soul to heal. Not thinking of doing anything—eating, running, making projects for the future, even for healing, practicing intensive meditation—all these things have to be stopped. No effort should be made either by the body or by the consciousness. We have to allow our body to really rest and also our consciousness. That is samatha, that is the practice of stopping and calming, and we have to learn it.

There are many of us who have no capacity for resting, of allowing our body and our mind to rest. That is because in us there is a very strong tendency to do something—running. We have run without stopping in the last four or five thousand years. It has become a habit. We even run in our dreams, during our sleep. So we have to start the practice of stopping. That is why practicing being in the present moment, touching the wonders of life that are present in this moment, is a very wonderful and easy way of resting.

There’s a tendency for us to think that our happiness should be searched for in the future, by doing something. Even our health should be “searched for” by doing something. But we don’t know that not doing anything may be the key to restoring our health. Many of us are obsessed by the idea that we have to get more nutrients. We buy vitamins, “one-a-day,” and we take one pill every morning and things like that. Many of us are motivated by that kind of desire. Not many of us are aware that we have a reserve in our body that we can use for up to three or four weeks without eating. Those of us who practice fasting and drinking only water, can go for many weeks and we don’t have to stop the daily things. We can still go to sitting meditation, walking meditation, cleaning in the kitchen, in the bathroom, participating in Dharma talks. We can do that many weeks without eating. In the process, we enjoy doing these things. And the toxins we have, from the third day on, begin to get out because we are drinking a lot of water, we are practicing a lot of walking meditation and deep breathing and we clean our bodies, so the toxins can get out. And after three weeks, you look much better—even if you don’t eat anything. Your skin, the expression on your face, your smile—you may look like a new person. That is not because you take a lot of vitamins, or eat a lot of nutrients, it is because you don’t eat anything. You allow your body to rest.

The same thing is true of your consciousness. There are a lot of toxins within that have been accumulating over the years. We have ingested the toxins—the fear, the craving, the anger, the despair—in our daily life by touching this or that without mindfulness. So all these poisons have brought into being our depression, our anxiety, our sorrow—and this kind of garbage should be transformed, eliminated. If only we could allow ourselves to touch the refreshing and healing elements in our daily life, a process of detoxification would take place. Are you able to breathe in and to breathe out, and enjoy it? Just breathing in and breathing out. Is there anything interesting in breathing in and breathing out? Breathing in and breathing out is a wonderful thing. You are alive. The fact that you are breathing in is already a miracle. There are many people who want to breathe in but they cannot breathe in because they are already dead. We want them to breathe in but they lie there, lifeless. So to allow your body to breathe in and to become aware that you are breathing in, that you are alive, can be a source of deep happiness.

This morning I practiced like that in sitting meditation. When you breathe in, you might touch nature around you; when you breathe out, you allow yourself not to do anything, you rest completely.

[Bell]

The practice of samatha, stopping, is the practice of doing nothing—trying not to do anything, just allowing your body and your mind to rest. We know that it’s not easy, because we have already a habit of running and working, both in our body and in our mind. That is why putting yourself in a Sangha where there are people who are able to stop is very important. When you come to a retreat, where there are people who have the capacity of stopping, of being there in the present moment, you can profit from their presence, their energy. They are able to be happy with the blue sky, with a little flower blooming in the grass, with each step they make. Happiness is being manufactured every moment. They don’t run; they are able to stop and to live deeply every moment of their daily life. It’s very important that we find ourselves among those people, because touching them, we will be able to do the same after some time.

When you are on your cushion or walking, you just practice breathing in or breathing out in order to be there, just to be there. Because your mindful presence is the agent of love and care for the pain, for the suffering in you. You have not been there for yourself. You have been running and you have neglected yourself. To be loved means to be embraced by the attention, by the energy, of the person you love. When the animal stops and lies down, it’s doing that for itself. It allows itself time to rest and to heal—it is there for itself. We have to be there for ourselves. We are wounded, perhaps even deeply wounded in our body and in our soul. Who will be there for us? We have to be there for ourselves first. And the Buddha will be there for us, because the Buddha is inside of us.

To be able to establish oneself in the present moment, to know what is going on in that moment, to touch everything that is happening in that moment, is the practice. It does not require a lot of struggle; it does not require any struggle at all. Just allow yourself to be. There is a tendency to think that happiness, health, success are things you have to run to in order to get. That is why we have sacrificed the present moment. We have viewed the present moment as a means to get things in the future. That is a tendency to be stopped.

We are committed to a certain idea of happiness. We think that if we cannot realize this or that, if we cannot change this or that, then happiness will never be possible. Because of our commitment to that idea of happiness, we are not at peace with ourselves. We are trying to do something, to realize something, but maybe happiness is already there. All the conditions for you to be happy are already there. You need to recognize them. How can you recognize them if you are not there?

Maybe you have not realized that the sun in the sky is a condition for your happiness. Just take one second to look, and you see that all life on Earth is possible because of the sun. All our food comes from light, from the sun. And when you look at the sun like that, you see the sun as your father, your mother—it is nourishing you every day. The sun is always there for you. And you might complain that “nobody is taking care of me, nobody loves me, nobody pays attention to me,” but the sun is one thing that is nourishing you every second of your daily life.

The earth, the trees, the water, the air, the baker, the farmer, the birds, the insects. There are those of us who have practiced stopping and dwell in the present moment, and we are able to touch the many conditions of our happiness that are available in the here and the now. We find out that we don’t need more, because these conditions are more than enough to be happy. Stopping is very important. As long as you continue to run, happiness is very difficult. Stopping. Stopping allows your body and your mind to rest. Stopping allows you to recognize the conditions for your happiness that are already there.

The two elements of Buddhist meditation are stopping and looking deeply. You can only look deeply into the nature of things when they are there, when you are able to stop. Samatha is stopping, calming, and vipasyana is looking deeply. Sometimes you only need to stop, and suddenly a deep vision of reality will come like that. When the waves on the lake are calm, the surface of the lake is calm without waves, the full moon just reflects in the lake—the lake doesn’t have to run and look for the moon. Allow yourself to be in the present moment; enjoy touching the refreshing and healing elements that are around you and within you. Whether we believe they are or are not there, they are there. Allowing yourself to touch these healing elements will allow the garbage to become compost, and the flowers to reappear in the garden of your heart.

When you are there for yourself, there is an energy that embraces you, embraces your pain, embraces your suffering, your fear, your despair. It also embraces the good, positive qualities within you. The capacity of being joyful again, of being happy again, of being loving and tolerant—these qualities are within us, and they need to be embraced in order to grow; these are flowers. And the fear, despair, and sorrow in us need to be embraced in order to become compost. They will nourish the flowers. The Buddha needs Mara in order to grow beautifully as a flower and also Mara needs the Buddha, because Mara has a certain role to play.

So suffering is very important for your happiness. You cannot understand, you cannot love, until you know what suffering is. The joy of having something to eat is possible only if you know what hunger is. In some areas of China, when people meet each other, instead of asking, “How do you do?” or “How are you?” they ask, “Have you eaten yet? Have you gotten something to eat?” Because we know there is hunger, death. So our love is expressed in a very simple way: Have you eaten yet? Have you gotten anything to eat yet?

The tendency is to want to remove and to clear away the blocks of pain and sorrow and despair in us. We just want the Buddha or God to be like a surgeon who can cut out anything we don't want of ourselves, get it out of our system. In the light of non-duality, not only are we flowers, but we are also the garbage in us. We cannot just get rid of us. Sometimes we are love, sometimes we are anger; love is us, but anger is also us. So we have to treat both love and anger on an equal basis, like the Buddha was treating Mara. Mara didn't understand. Ananda also didn't understand. But the Buddha, he understood. He was teaching both of them the nature of non-duality between suffering and happiness.

The energy of mindfulness is the energy that allows us to be in the present moment, to embrace ourselves, our suffering, our despair, our sorrow; and also the seeds of joy and peace and love that have become weak in us because we have not been able to water and cultivate these seeds to help them to be stronger. So the practice is the practice of embracing, and it is clear that the energy with which you can embrace yourself is the energy of mindfulness. “Darling, I am there for you.” When we love someone we want to make such a declaration, “Darling I am there for you.” And you have to be really there for her. Your presence is the greatest gift you can make to the person you love. To be there, it's not easy. You have to be there with one hundred per cent of yourself. You have to be really mindful, with all your attention. That energy has the power of healing and of making the other person happy. In this case it is self-love, and we all know that the love we have for another depends on our self-love. If we know how to take care of ourselves, if we know how to nourish and to transform ourselves, we will be able to take care of the other person. So the object of love is our self first—our body and our consciousness. Embracing yourself in the present moment is the practice.

By being there entirely, you recognize that not only suffering is there, something else is there—the wonders of life, the refreshing and healing elements from within and around and you may like to practice touching them. Look at the sky; listen to the rain, smile to it. It's wonderful that it's raining, it's wonderful that the sky is blue this morning, it's wonderful that I am here, alive. It's wonderful that I can walk, it's wonderful that my heart still functions normally. There are so many things you can enjoy. When one tree in the garden dies you may forget that all the other trees are still alive. You let your sorrow dominate, and suddenly you lose everything. When a tree is dying in my garden, yes, I know it, but there are other trees that are still green, healthy. If you remember that, you will not be drowned by your sorrow, and you will have enough strength to save the tree that is dying or replace it with another tree.

Make your heart large so that you may be able to see that the conditions for your happiness are there, and injustice, cruelty, or meanness is not enough to ruin your life. You can accept it easily, because your heart is large, and you can receive it without resentment and anger. It's like when you throw some dirt into the river, the river would not be angry. The river is willing to accept that dirt, and it can transform that dirt overnight. There's so much water in the river, so much mud in the water that the amount of dirt that you throw into the river will be transformed overnight. If you throw that dirt into a container of water in your home that would not be the same thing. You know that the water in the container will no longer be drinkable, you have to throw it away. But when you throw that amount of dirt into the river, people from the city still continue to drink the water from the river because it’s large. The river has the capacity of transforming and healing. So practice being like a river, that is what the Buddha recommended to us.

Practice being like the earth. Whether people throw on earth flowers, perfumes, rice, curries or they throw on it urine, excrement, the earth will be willing to accept all without any resentment, because earth is large and earth has the power to transform. And earth is always there for us. So the Buddha told Rahula, “My dear, practice like earth, practice like water in the river and you will not suffer because your heart is big.”

So coming back to embrace ourselves, to start the process of healing, to touch the positive elements does not seem to be a difficult practice. You only need a Sangha where there are people who are doing that and who enjoy just doing that. When you come to the Meditation Hall and sit down holding your plate of food, you may do it with a lot of pleasure. Don't think of it as a hard practice. Yes, we don’t talk during the whole meal, you sit quiet in an erect position during the whole meal. Yes, we do that. But many of us enjoy doing that. We don't have to talk, we don't have to think, we don't have to do anything: we just realize complete rest during the whole meal. To be able to share a meal with a Sangha in mindfulness, not to have to do anything at all, to just enjoy every morsel of your food, touching your food deeply without any thinking, without making any project in your mind is the practice, the practice of stopping and resting.

You may think that it's oppressive not to talk. It's difficult to stay in a sitting position like this for one hour, but that is because you are so used to running and to doing movements. But to allow yourself to sit for one hour, not (indiscernible words) enjoy our upright position, enjoy our in-breath and our out-breath, not to think of anything, just enjoy. Because being there sitting, not doing anything is a very nice thing to do, and just to be aware of our in-breath and our out-breath, and just to relax the muscles on our face, our body, is a nice thing to do.

When you pick up a piece of string bean, look at it, smile, and call it by its true name, “string bean.” And you realize with some mindfulness and concentration that the piece of string bean is a wonder of life, exactly like you—you are a wonder of life, you are a miracle. The piece of string bean has been made by clouds, sunshine, the earth, the minerals, the air, the water, everything. This piece of string bean is really an ambassador coming to you from the cosmos if you know how to receive it, how to be with it, how to chew it mindfully and joyfully. Eating a piece of string bean may give joy. What is the use of eating a piece of string bean? To get nutrition? No, you just enjoy the piece of string bean, you enjoy yourself, the presence of the bean, you enjoy the moment, being with yourself and with the Sangha.

We like to chew our food thirty times, forty times, fifty times. During that time we don't chew anything else, we don't chew our projects, our sorrow, our anxiety. Allow it to sleep, you are embracing it now by the practice of being there, mindful. Eating is a practice, a practice of not doing anything, a practice of stopping. And with some intelligence, we can make the time of eating a time of joy. It may be oppressive not talking, not laughing, not making movements. But they are only the habits; you have to learn the habit of resting, it's very important.

Sitting on your cushion during sitting meditation is also practicing resting, and practicing walking meditation, just touching the earth and realizing the wonder of being alive and walking on the earth, this is also the practice of resting. In every moment you allow yourself to be there and to take care of your sorrow, your anxiety, your pain. They may be sleeping quietly down there in the bottom of your consciousness, or they may be emerging on the surface. In any case, embrace them; embrace them with your true presence, because the energy of mindfulness is the energy of being there for you, for the people you love. The sun is there for you, the moon is there for you, the trees are there for you, the water is there for you, and you should be there for them also, especially for yourself. You are the person who needs you the most. Call your name, call your name in silence—that person has suffered, that person needs you desperately, you should go back and embrace her, embrace him.

[Bell]

Now let us do a meditation exercise. Let us visualize ourselves as young people who are caught in a situation of drugs. There are so many young people who are addicted to drugs in Europe, in America, everywhere. This is a big problem of the twentieth century, and we don't know whether we will be able to solve it during the first half of the twenty-first century. This is some garbage that needs to be taken care of. Who are these young people who every day seek desperately to have some money to buy some drugs? Even if you know how to get some drugs, you don't know how to get the money. You may have tried to steal the money from your parents, which is safer than stealing from other people.

There are so many of us who suffer in Europe, in Asia, in America. We are suffering, we are despair, we are sorrow, we need to be embraced. We are the garbage of humanity. We want to go back to being flowers. Who will help us? What kind of presence could be given to us? We suffer; we don't need suppression, we don't need the army, we don't need the police. We really need a kind of presence that helps us to transform, because we don't want to be in this position. But we are in this position, a position where we have to seek every day a means to get some drugs. Where is humanity? Who can help us? Who can manifest their true presence in order to embrace us? Who knows that we are suffering? They think that we only need punishment. They don't know how difficult it is for us to get out of our situation.

The energy that we need is enlightenment, is mindfulness. We need people to know that we suffer, that we don't want to be like this for a long time, because maybe tomorrow it will be too difficult for us to continue and we may have to kill ourselves. So we need desperately some kind of presence that tells us they know that we are there, we suffer and they are there for us.Who are they? People in the church, they don't really want to do something to help us. Our parents, what have they done for us to be like we are today? It's not because we just want to be addicted to drugs, it's because we have suffered so much. We feel wounded, we feel no way out, that we have to look for some drugs to be able to forget our situation.

The people in the Church don't seem to understand us. There may be nice people in the Church, they may want to do something, but in a majority of the cases they are preaching to us a kind of teaching that cannot respond to our real need. They are trying to impose on us the kind of life that does not seem to fit us. Understanding and compassion does not seem to come from the direction of the Church.We have practiced and our teacher says that we have to go back to our spiritual roots. We have tried. We had to start, we have started to going back to Mass but still, they are still narrow-minded. They don't know what our suffering is.

Our parents, they don't seem to be happy with each other. They make each other suffer. They created hell in our family. We have not been able to see happiness in the family. We have not experienced harmony, compassion and love in our family life. They don't seem to understand us. They don't seem to love us. How could love be possible without understanding? We don't see anything beautiful in this life. Everything is ugly. We don't see anything meaningful in this life. We don't see anything true in this life, everything seems to be fake. So we are hungry ghosts, looking for something meaningful and true. Since we have not found anything, we have to forget we are there and drugs seem to be the only thing for us. This is a block of garbage produced collectively during the twentieth century.

Meditation on this scale means to produce a presence of enlightened people—governmental people, doctors, psychotherapists, educators, artists and so on. We have to come as a group, as a Sangha, to produce our true presence. “Dear people, we know that you are there, we know that you suffer, that is why we have come to you and embrace you, not with the intention to punish or to blame, but just to embrace you. We want to understand you better; we want to love you.” That is the presence they need: that is collective meditation. Maybe in coming together our insight will be deep enough to provide these people with a positive environment for their healing and their liberation—a healing center, rehabilitation center, where these young people can get the minimum dose of drugs they need every day so that they don't have to go and kill or steal in order to get the drugs. Where they can be taken good care of, and get help in order to reduce the amount of drugs and start the process of healing, touching the things that surround us that are healthy, that are refreshing.

If those of us who are doctors, governmental people, artists, psychotherapists don't practice for ourselves, we won't have insight and compassion and understanding; how can we help take care of the garbage we have produced? Who is responsible for producing this garbage? All of us. Blaming other people will not help, especially blaming the victims. We have to realize that they are us, we are them, that our life is made of flowers and garbage at the same time. We have to accept both and to take care of both in the best way that we can, with the understanding, the calm, provided by our practice.

The government of Holland has tried to do things, the government of France, of Spain, many governments; the government of the United States of America also has tried many ways to help. But where are we? Haven't we realized that we are responsible for the production of the garbage? Our society is produced in such a way that we create hungry ghosts very young, every day, by the thousands, by the hundreds of thousands. They are everywhere, wandering around without anything to believe in, without anything to love, without anything that looks true and good and beautiful.

I don't know whether during the first half of the twenty-first century we can handle this problem of drugs, of the hungry ghosts that we produce. We have to call on people in all walks of life—parents, Church, teachers, businessmen and others—to stop and look. This is very important, stopping and looking at our present situation and considering how to start transforming garbage into flowers. We have to organize Dharma discussions on a very big scale. We have to organize it in our family, we have to organize it in our city, we have to make it into a national debate where people may have a say, where each person makes a contribution of his or her insight. That is a matter for all of us, that is meditation.

As individuals we have problems; but we also have problems as families, as cities, as nations, and meditation in the twenty-first century should be a collective practice. Without a Sangha we cannot achieve much. When we focus our attention on suffering, on the garbage on a larger scale, maybe the little problems that we have within our individual circle will vanish, because by practicing being there we begin to connect with, to relate to, other people who are also ourselves. That way our loneliness, our feeling of being cut off, will no longer be there, and we will be able to do things together. Like when we come to Plum Village, we try to be part of the Sangha, we practice as a Sangha. It's much easier, and transformation will take place much more quickly if you don't just practice as individuals. When I practice walking I make mindful and beautiful steps. I know that I do that not only for myself, but also for all of my friends who are here; because everyone, who sees me taking a step like that has confidence and is reminded to do the same. And when they make a step in the present moment, smiling and making peace with themselves, they inspire us all, they are doing that for all of us. You breathe for me, I walk for you, we do things together and this is practicing as a Sangha.

So today please enjoy your walking if it doesn't rain. If it rains, you enjoy the rain. We also have a formal meal together. A formal meal is a time when we sit together as a Sangha, we enjoy the collective energy of mindfulness, and each of us allows the mindful energy of the Sangha to penetrate in. Even if you don't do anything, just stop thinking and allow yourself to absorb the collective energy of the Sangha. It's very healing. Don't struggle, don't try to do something. Allow yourself to rest, and the energy of the Sangha will help. Eat your meal very slowly, mindfully; enjoy every morsel of food. That is the most important thing to do during eating, just enjoy every morsel of food, chew it carefully and slowly. That allows the pain, the sorrow in us to be embraced.





* * *



Dear Friends,

These dharma talks transcriptions are teachings given by Venerable Thich Nhat Hanh in Plum Village or at various retreats around the world. The teachings cover all areas of concern to practitioners: from dealing with difficult emotions to realizing the Interbeing nature of ourselves and much more.

This project relies on generosity (Dana) so that these talks can continue to be made available to all. You may forward and redistribute them via email, and you may also print them and distribute them to members of your Sangha. This work is licensed under a [Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License](http://creativecommons.org/licenses/by-nc-nd/3.0/deed.en_US). [![Creative Commons License](http://i.creativecommons.org/l/by-nc-nd/3.0/88x31.png)](http://creativecommons.org/licenses/by-nc-nd/3.0/deed.en_US)

If you would like to make a donation so we may continue this works, please click on [ Donate ](http://plumvillage.org/donate/ ) to Unified Buddhist Church.

Your skills of transcribing the Dharma talks are valuable to us. Please, visit our [Audio Archives](http://tnhaudio.org) and select the Dharma Talk which you would like to transcribe. Please send us an email first so we can tell you whether or not your choice is already being transcribe by someone else. For information regarding the Transcription Project please contact us at Plum Village Webmaster via: [Contact Us](http://plumvillage.org/contact-us/)


